runtime: python311

env_variables:
  EMPL_ID: "24386186"
  LAST_NAME: "Hiba"
  GOOGLE_AI_STUDIO_API_KEY: "AIzaSyCWzBH7W3grKzhkxePtuQK5Ljp1cYZ2OVo"

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT
