runtime: python311

env_variables:
  EMPL_ID: "24386186"
  LAST_NAME: "Hiba"
  # GOOGLE_AI_STUDIO_API_KEY will be set via cloud shell environment variable
  # Set it using: gcloud app deploy --set-env-vars GOOGLE_AI_STUDIO_API_KEY=your_key_here

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT
